import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";
import NavbarWrapper from "@/components/NavbarWrapper";
import FooterWrapper from "@/components/FooterWrapper";
import { SidebarProvider } from "@/lib/SidebarContext";

export const metadata: Metadata = {
  title: "NextJS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className="flex flex-col min-h-screen bg-gray-50">
        <SidebarProvider>
          <NavbarWrapper />
          <LayoutWrapper>{children}</LayoutWrapper>
          <FooterWrapper />
        </SidebarProvider>
      </body>
    </html>
  );
}
